export const data = [
  {
    model: "IPhone 10",
    brand: "Apple",
    description: "Old, like mammoth shit, some expensive hype phone",
    prise: 5000,
    img: "iphone-10.png",
  },
  {
    model: "IPhone 11",
    brand: "Apple",
    description: "Not very old some expensive hype phone",
    prise: 7540,
    img: "iphone-11.jpg",
  },
  {
    model: "IPhone 12 PRO",
    brand: "Apple",
    description: "New, but mammoth shit, some expensive hype phone",
    prise: 999999,
    img: "iphone-12-pro.png",
  },
  {
    model: "Huawei Mate 10 PRO",
    brand: "Huawei",
    description: "Some old no-name china phone",
    prise: 3500,
    img: "huawei-mate-10-pro.jpg",
  },
  {
    model: "Huawei Mate 20 PRO",
    brand: "Huawei",
    description: "Some not so old no-name china phone",
    prise: 5500,
    img: "huawei-mate-20-pro.webp",
  },
  {
    model: "Xiaomi Redmi 9 PRO",
    brand: "Xiaomi",
    description: "Old, but good for your money, china phone",
    prise: 6500,
    img: "xiaomi-9-pro.jpg",
  },
  {
    model: "Xiaomi Redmi 10 PRO",
    brand: "Xiaomi",
    description: "Not so old, but good for your money, china phone",
    prise: 8300,
    img: "xiaomi-10-pro.jpg",
  },
  {
    model: "Xiaomi 11 ULTRA",
    brand: "Xiaomi",
    description: "Super china phone",
    prise: 8300,
    img: "xiaomi-11-ultra.jpg",
  },
];
